baseURL: "https://emilienakotenou.github.io/" 
title: Emilien Akotenou
paginate: 14
theme: PaperMod

enableInlineShortcodes: true 
enableRobotsTXT: true  

social:
    twitter: e_akotenou

taxonomies:
    tag: tags

menu:
    main:
          - name: Teaching
            url: /courses/
            weight: 1
          - name: Research
            url: /papers/
            weight: 2
          - name: Code
            url: /code/
            weight: 3            
          - name: CV
            url: /cv.pdf
            weight: 3
        #   # weight: 1
        # - name: Design
        #   url: /design/
        #   weight: 3
        # - name: Tags
        #   url: /tags/
        #   weight: 5     
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: |
               <div style="margin-bottom: 0.2cm;"></div>
               Welcome! 
               <div style="margin-bottom: 0.5cm;"></div>
               I am an Assistant Professor of Economics at the University of Wisconsin-La Crosse Department of Economics.
               <div style="margin-bottom: 0.5cm;"></div>
               I am an applied microeconomist with interests in labor economics, economics of education, and health economics. My primary research interest examines how institutional policies and resources affect student outcomes in higher education, focusing on college costs, sports, and amenities. Additionally, I study public health policies, particularly investigating vaccination programs' impacts on maternal and infant health outcomes, and the relationship between substance legalization and healthcare decisions. I received my PhD in Economics from the University of Oklahoma-Norman.
               <div style="margin-bottom: 0.5cm;"></div>    
    author: Emilien Akotenou
    DateFormat: "January 2024"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true 
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true  
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true 
    ShowWordCount: false
    UseHugoToc: true 
    comments: false
    math: true
    profileMode:
          enabled: true 
          title: "<span style='font-size: 26px;'>Ahmed El Fatmaoui</span>"
          subtitle: |
               <div style="margin-bottom: 0.2cm;"></div>
               Welcome! 
               <div style="margin-bottom: 0.5cm;"></div>
               I am an Assistant Professor of Economics at the University of Wisconsin-La Crosse Department of Economics.
               <div style="margin-bottom: 0.5cm;"></div>
               I am an applied microeconomist with interests in labor economics, economics of education, and health economics. My primary research interest examines how institutional policies and resources affect student outcomes in higher education, focusing on college costs, sports, and amenities. Additionally, I study public health policies, particularly investigating vaccination programs' impacts on maternal and infant health outcomes, and the relationship between substance legalization and healthcare decisions. I received my PhD in Economics from the University of Oklahoma-Norman.
               <div style="margin-bottom: 0.5cm;"></div>
          imageUrl: "/picture.jpeg"
          #imageWidth: 280
          #imageHeight: 300
          imageWidth: 245
          imageHeight: 250
          imageTitle: Emilien Akotenou
          #imageTitle: "<span style='font-size: 12.5px;'>Ahmed El Fatmaoui</span>"
          buttons:
              - name: Teaching
                url: /courses/
                weight: 1
              - name: Research
                url: /papers/
                weight: 2
              - name: Code
                url: /code/
                weight: 3                
              - name: CV
                url: /cv.pdf
                weight: 3
              # - name: Design
              #   url: /design/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:eakotenou@ou.edu
        - name: Location
          url: /location/
        # - name: Office Hours
        #   url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=EdHxr3EAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ahmedelfatmaoui?tab=repositories
        - name: Linkedin
          url: https://www.linkedin.com/in/ahmed-el-fatmaoui-75114b330/
        - name: Twitter
          url: https://x.com/ahmedelfatmaoui

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true # Set to true to hide cover images in paper
        hiddenInSingle: true
    label:
      text: "Emilien Akotenou"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: true
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120â€“155
# * summary: 265




